server:
  port: 8102

###服务别名--该服务注册到服务中心的名称
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ### 定义转发规则，这里的api-a是自定义的,也可以修改为api-member
    api-a:
      ### 客户端请求http://127.0.0.1/api-member开头的，都会转发到会员服务
      path: /api-member/**
      #这里的app-member是会员服务在注册中心中的别名
      #zuul网关默认整合ribbon,自动实现负载均衡轮训效果
      serviceId: app-member
    api-b:
      path: /api-order/**
      serviceId: app-order


eureka:
  client:
    serviceUrl:
      ###当前会员服务注册到eureka服务中心（所有eureka集群地址）
      defaultZone: http://eureka-server1:7100/eureka/
