spring:
  application:
    name: service-gateway

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://127.0.0.1:8091
          predicates:
            ## 当请求的路径为gate、rule开头的时，转发到http://localhost:9023服务器上
            - Path=/gate/**,/rule/**
          ### 请求路径前加上/app
          filters:
            - PrefixPath=/app

server:
  port: 9000

