server:
  port: 8102
eureka:
  client:
    serviceUrl:
    ###当前会员服务注册到eureka服务中心（所有eureka集群地址）
      defaultZone: http://eureka-server1:7100/eureka/,http://eureka-server2:8100/eureka/,http://eureka-server3:9100/eureka/
    ###需要将本服务注册到eureka上
    register-with-eureka: true
    ###需要去检索服务信息
    fetch-registry:   true

### swagger扫包范围
swagger:
  base-package: api.member.servcie.impl
