spring:
  application:
    ###服务别名
    name: order-service
  cloud:
    nacos:
      discovery:
        ##注册中心地址
        server-addr: 192.168.1.129:8845
        group: LXF_GROUP

server:
  port: 8099

