server:
  port: 8103
###服务别名--该服务注册到服务中心的名称
spring:
  application:
    name: app-order
eureka:
  client:
    serviceUrl:
      ###当前会员服务注册到eureka服务中心（所有eureka集群地址）
      defaultZone: http://eureka-server1:7100/eureka/
    ###需要将本服务注册到eureka上
    register-with-eureka: true
    ###需要去检索服务信息
    fetch-registry:   true
