server:
  port: 8103
###服务别名--该服务注册到服务中心的名称
spring:
  application:
    name: app-order
eureka:
  client:
    serviceUrl:
      ###当前会员服务注册到eureka服务中心（所有eureka集群地址）
      defaultZone: http://eureka-server1:7100/eureka/
    ###需要将本服务注册到eureka上
    register-with-eureka: true
    ###需要去检索服务信息
    fetch-registry:   true

### SpringCloud feign 默认开启支持ribbon负载均衡
ribbon:
  ##建立连接时需要的时间5秒, 适用于网络状态正常情况下,两端连接所用的时间
  ReadTimeout: 5000
  ##建立连接后从服务器读取到可用资源所用的时间,默认1秒,这里配置5秒
  ConnectTimeout: 5000

### 开启Hystrix断路器
feign:
  hystrix:
    enabled: true

### 禁用hystrix超时时间,默认1秒
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true

