server:
  port: 8101

###服务别名--该服务注册到服务中心的名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #configServer 读取git环境的地址
          uri: https://github.com/liangxifeng833/gkconfig.git
          #查找会员服务配置文件，git中的目录名
          search-paths:
            - member-config
          #读取git的分支
          label: master

eureka:
  client:
    serviceUrl:
      ###当前会员服务注册到eureka服务中心（所有eureka集群地址）
      defaultZone: http://eureka-server1:7100/eureka/
    ###需要将本服务注册到eureka上
    register-with-eureka: true
    ###需要去检索服务信息
    fetch-registry: true

